name: "isolation_forest"
backend: "python"
max_batch_size: 256
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 6 ]
  }
]
output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [ 1 ]
  },
  {
    name: "label"
    data_type: TYPE_INT32
    dims: [ 1 ]
  }
]
